### ISSUE TITLE
Checking Web Site for Broken Links

### ISSUE THREAD

**Issue by aksarben** [microsoft/linkcheckermd#59]
Sorry if this isn’t the right place to post this. I was sent here by a **Ask a Question** button on another page.

Can this Visual Studio Code extension check an entire Web site for broken links? The documentation I’ve seen only seems to deal with checking a single Web page at a time, which is impractical for a large site like mine.

**Comment by aksarben** [comment]
It didn’t even update the opened file. I was watching as I renamed the target in the folder pane, and there was no change to the href in the open file.


___________________________

The Cyber Hymnal™ <><
http://www.hymntime.com/tch
________________________________

**Comment by Blackmist** [comment]
@aksarben This extension doesn't monitor for changes to the document. Instead, it has to be ran manually. For example, setting to a hotkey such as alt + L. Running it parses the markdown file currently open in VSCode and tries to validate the links. It then generates a report of the problem links.

**Comment by aksarben** [comment]
Ok. So  checks only the currently open file.

I'm considering migrating from Expression Web 4 (EW4), which updates all the files in a project within a few seconds. But that comes with a price: For every file in the project, EW4 maintains a metadata file that records links to and from the source code file. A lot of overhead disk-space-wise, but greatly improved performance. Makes a huge difference to large Web sites such as ours.

Dick Adams

___________________________

The Cyber Hymnal™ <><
http://www.hymntime.com/tch
________________________________
